@startuml

class Tablero {
    +void print()
}

class Accion {
    +void mover()
    -string celda
    -string direccion
}

class Celda {
    +std::string print()
    -int fila
    -int columna
}

class Ficha {
    +std::string print()
    -bool oponente
}

Jugador --> Accion
Accion --> Tablero

Tablero *--> "8x8" Celda
Celda o--> "0..1" Ficha
Ficha <|-- FichaO
Ficha <|-- FichaX

Tablero --> EstadoInicial
Estado <|-- EstadoInicial
Estado <|-- EstadoFinal

@enduml